POST http://localhost:8080/api/google-auth
Content-Type: application/json

{
  "authCode":"4/0AWtgzh7pDfVO3P4Go2td_uh-MV5yJsJYmTEJR72-K-sMrpSq6tnffuFY8J63PAAlE3gpCg"
}

###
POST http://localhost:8080/api/apple-auth
Content-Type: application/json

{
  "authCode":"ce0310b9b340c4df287d9b73f069ff9d9.0.svqy.3eE-DMbFbYUCtCeEgsIM-A"
}