POST https://eveningpopcorn.dev/api/v1/auth/social/login
Content-Type: application/json

{
  "oauth_type": "apple",
  "auth_code": "c47c896beeeac47d5a0a3ddd8b36973ad.0.svqy.brbhVawP8bj6P38QVQZLXA"
}

###
GET https://eveningpopcorn.dev/api/v1/movie/1111
Content-Type: application/json
X-Token: KtCa1ePxTOHVEED2bEiEkdnfNzZdsLpNSbri8cRWVdN0HCcuQ9u2x3SYoNI8Wpnc

###
GET localhost:8080/api/v1/movie/161
Content-Type: application/json
X-Token: 6vTOATz2G3mlH4GOuPajmg1LM9LMl7EGLSijsy4Hj4DfFmEbfe6UnOsp17HiGzK0
###
GET localhost:8080/openapi.json
Content-Type: application/json
X-Token: 6vTOATz2G3mlH4GOuPajmg1LM9LMl7EGLSijsy4Hj4DfFmEbfe6UnOsp17HiGzK0

###
GET https://eveningpopcorn.dev/api/v1/movie/162
Content-Type: application/json
X-Token: KtCa1ePxTOHVEED2bEiEkdnfNzZdsLpNSbri8cRWVdN0HCcuQ9u2x3SYoNI8Wpnc
X-Language: ES
###
GET https://eveningpopcorn.dev/api/v1/movie/search?q=11+друзей
Content-Type: application/json
X-Token: KtCa1ePxTOHVEED2bEiEkdnfNzZdsLpNSbri8cRWVdN0HCcuQ9u2x3SYoNI8Wpnc
X-Language: RU
###
GET localhost:8080/api/v1/movie/search?q=11+друзей
Content-Type: application/json
X-Token: 6vTOATz2G3mlH4GOuPajmg1LM9LMl7EGLSijsy4Hj4DfFmEbfe6UnOsp17HiGzK0
X-Language: RU
###
GET https://eveningpopcorn.dev/api/v1/backlog/
Content-Type: application/json
X-Token: KtCa1ePxTOHVEED2bEiEkdnfNzZdsLpNSbri8cRWVdN0HCcuQ9u2x3SYoNI8Wpnc
X-Language: RU

###
POST https://eveningpopcorn.dev/api/v1/backlog/
Content-Type: application/json
X-Token: KtCa1ePxTOHVEED2bEiEkdnfNzZdsLpNSbri8cRWVdN0HCcuQ9u2x3SYoNI8Wpnc
X-Language: RU

{
  "movie_id": 162,
  "note": "asdasd"
}
###
DELETE localhost:8080/api/v1/backlog?movie_id=150
Content-Type: application/json
X-Token: 6vTOATz2G3mlH4GOuPajmg1LM9LMl7EGLSijsy4Hj4DfFmEbfe6UnOsp17HiGzK0
X-Language: RU
###
GET localhost:8080/api/v1/auth/me
Content-Type: application/json
X-Token: 6vTOATz2G3mlH4GOuPajmg1LM9LMl7EGLSijsy4Hj4DfFmEbfe6UnOsp17HiGzK0
X-Language: RU