GET {{host}}/v1/user-backlog?user_id={{user}}

###
GET {{host}}/v1/check-is-in-backlog?user_id={{user}}&movie_ids=161&movie_ids=162

###

POST {{host}}/v1/user-backlog
Content-Type: application/json

{
  "user_id": "{{user}}",
  "movie_id": 150,
  "note": "126"
}