POST localhost:8083/game-api/v1/create-game
Content-Type: application/json
X-Token: 6vTOATz2G3mlH4GOuPajmg1LM9LMl7EGLSijsy4Hj4DfFmEbfe6UnOsp17HiGzK0

{
   "name": "Test"
}

###
POST localhost:8083/game-api/v1/game/join
Content-Type: application/json
X-Token: oV3cfPdbZ178SAPDULEOnFNpQB5iJHdoQ3GwJjKHCdDyRVf5GDCrEn7oWbPWExRx

{
  "code": "Yd5YPnJa"
}

###
GET localhost:8083/game-api/v1/game?code=UkmmQGi2
Content-Type: application/json
X-Token: oV3cfPdbZ178SAPDULEOnFNpQB5iJHdoQ3GwJjKHCdDyRVf5GDCrEn7oWbPWExRx

###
POST localhost:8083/game-api/v1/game/movie
Content-Type: application/json
X-Token: 6vTOATz2G3mlH4GOuPajmg1LM9LMl7EGLSijsy4Hj4DfFmEbfe6UnOsp17HiGzK0

{
  "code": "Yd5YPnJa",
  "movie_id": 161
}

###
GET localhost:8083/game-api/v1/game/movie?code=9pE0zKzk
Content-Type: application/json
X-Token: 6vTOATz2G3mlH4GOuPajmg1LM9LMl7EGLSijsy4Hj4DfFmEbfe6UnOsp17HiGzK0
X-Language: RU

###
DELETE localhost:8083/game-api/v1/game/movie?code=9pE0zKzk&movie_id=76600
Content-Type: application/json
X-Token: 6vTOATz2G3mlH4GOuPajmg1LM9LMl7EGLSijsy4Hj4DfFmEbfe6UnOsp17HiGzK0
X-Language: RU

###
GET localhost:8083/game-api/v1/game/wait-start?code=Yd5YPnJa
Content-Type: application/json
X-Token: 6vTOATz2G3mlH4GOuPajmg1LM9LMl7EGLSijsy4Hj4DfFmEbfe6UnOsp17HiGzK0

###
POST localhost:8083/game-api/v1/game/start
Content-Type: application/json
X-Token: 6vTOATz2G3mlH4GOuPajmg1LM9LMl7EGLSijsy4Hj4DfFmEbfe6UnOsp17HiGzK0

{
  "code": "Yd5YPnJa"
}
###
GET localhost:8083/game-api/v1/game/roster?code=Yd5YPnJa&page=1
Content-Type: application/json
X-Token: 6vTOATz2G3mlH4GOuPajmg1LM9LMl7EGLSijsy4Hj4DfFmEbfe6UnOsp17HiGzK0
###
POST localhost:8083/game-api/v1/game/like
Content-Type: application/json
X-Token: 6vTOATz2G3mlH4GOuPajmg1LM9LMl7EGLSijsy4Hj4DfFmEbfe6UnOsp17HiGzK0

{
  "code": "Yd5YPnJa",
  "movie_id": 163
}