POST localhost:8083/game-api/v1/create-game
Content-Type: application/json
X-Token: 6vTOATz2G3mlH4GOuPajmg1LM9LMl7EGLSijsy4Hj4DfFmEbfe6UnOsp17HiGzK0

{
   "name": "Test"
}

###
POST localhost:8083/game-api/v1/join-game
Content-Type: application/json
X-Token: oV3cfPdbZ178SAPDULEOnFNpQB5iJHdoQ3GwJjKHCdDyRVf5GDCrEn7oWbPWExRx

{
  "code": "UkmmQGi2"
}

###
GET localhost:8083/game-api/v1/game?code=UkmmQGi2
Content-Type: application/json
X-Token: oV3cfPdbZ178SAPDULEOnFNpQB5iJHdoQ3GwJjKHCdDyRVf5GDCrEn7oWbPWExRx
