GET https://api.themoviedb.org/3/search/movie?api_key={{API_KEY}}&language=ru&query=11+друзей

###

GET https://api.themoviedb.org/3/movie/161?api_key={{API_KEY}}&language=ru&append_to_response=watch/providers,
###
GET https://api.themoviedb.org/3/movie/161/videos?api_key={{API_KEY}}&language=ru
###
GET https://api.themoviedb.org/3/movie/161/credits?api_key={{API_KEY}}&language=ru
###
GET https://api.themoviedb.org/3/movie/161/watch/providers?api_key={{API_KEY}}&language=ru