apiVersion: apps/v1
kind: Deployment
metadata:
  name: moviegeek-deployment
  labels:
    app: moviegeek
spec:
  replicas: 3
  selector:
    matchLabels:
      app: moviegeek
  template:
    metadata:
      labels:
        app: moviegeek
    spec:
      containers:
        - image: registry.digitalocean.com/evening-popcorn-registry/moviegeek:latest
          imagePullPolicy: Always
          name: sample-container
          ports:
            - containerPort: 8080
              name: fastapi
          readinessProbe:
            httpGet:
              port: 8080
              path: /
            initialDelaySeconds: 15
          livenessProbe:
            httpGet:
              port: 8080
              path: /
            initialDelaySeconds: 15
            periodSeconds: 15