on:
  push:
    paths:
      - api-gateway/**
    branches:
      - main
jobs:
  build:
    name: Build api-gateway image
    runs-on: self-hosted
    env:
      IMAGE_NAME: api-gateway
      TAG: latest
    steps:
      - uses: actions/checkout@v3
      - name: Building image
        run: |
          cd api-gateway
          docker build -t $IMAGE_NAME:$TAG .
          docker image tag $IMAGE_NAME:$TAG registry.digitalocean.com/${{ vars.REGISTRY_NAME }}/$IMAGE_NAME:$TAG
          docker push registry.digitalocean.com/${{ vars.REGISTRY_NAME }}/$IMAGE_NAME:$TAG
  deploy:
    needs: build
    name: Deploy api-gateway to K8s
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to K8s
        run: kubectl apply -f api-gateway/deploy/manifest.yaml